--SEQUENSE
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE_TOKEN FOR I16D.SEQ_VALUE_TOKEN;
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE_URL FOR I16D.SEQ_VALUE_URL;
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE FOR I16D.SEQ_VALUE;
CREATE PUBLIC SYNONYM I16D_SEQ_ARCHIVE_CONFIG FOR I16D.SEQ_ARCHIVE_CONFIG;
CREATE PUBLIC SYNONYM I16D_SEQ_CONTENT FOR I16D.SEQ_CONTENT;
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE_ARCHIVE FOR I16D.SEQ_VALUE_ARCHIVE;
CREATE PUBLIC SYNONYM I16D_SEQ_GROUPER FOR I16D.SEQ_GROUPER;
CREATE PUBLIC SYNONYM I16D_SEQ_ERROR FOR I16D.SEQ_ERROR;
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE_CREDENTIAL FOR I16D.SEQ_VALUE_CREDENTIAL;
CREATE PUBLIC SYNONYM I16D_SEQ_VALUE_CERTIFICATE FOR I16D.SEQ_VALUE_CERTIFICATE;
CREATE PUBLIC SYNONYM I16D_SEQ_ARCHIVE_TYPE FOR I16D.SEQ_ARCHIVE_TYPE;
CREATE PUBLIC SYNONYM I16D_SEQ_ARCHIVE_MAPPER FOR I16D.SEQ_ARCHIVE_MAPPER;
--TABLE
CREATE PUBLIC SYNONYM I16D_ARCHIVE_CONFIG FOR I16D.ARCHIVE_CONFIG;
CREATE PUBLIC SYNONYM I16D_ARCHIVE_MAPPER FOR I16D.ARCHIVE_MAPPER;
CREATE PUBLIC SYNONYM I16D_ARCHIVE_TYPE FOR I16D.ARCHIVE_TYPE;
CREATE PUBLIC SYNONYM I16D_CONTENT FOR I16D.CONTENT;
CREATE PUBLIC SYNONYM I16D_ERROR FOR I16D.ERROR;
CREATE PUBLIC SYNONYM I16D_GROUPER FOR I16D.GROUPER;
CREATE PUBLIC SYNONYM I16D_VALUE FOR I16D.VALUE;
CREATE PUBLIC SYNONYM I16D_VALUE_ARCHIVE FOR I16D.VALUE_ARCHIVE;
CREATE PUBLIC SYNONYM I16D_VALUE_CERTIFICATE FOR I16D.VALUE_CERTIFICATE;
CREATE PUBLIC SYNONYM I16D_VALUE_CREDENTIAL FOR I16D.VALUE_CREDENTIAL;
CREATE PUBLIC SYNONYM I16D_VALUE_TOKEN FOR I16D.VALUE_TOKEN;
CREATE PUBLIC SYNONYM I16D_VALUE_URL FOR I16D.VALUE_URL;
--VIEW
CREATE PUBLIC SYNONYM I16D_VALUE_CERTIFICATE_VIEW FOR I16D.VALUE_CERTIFICATE_VIEW;
--MANAGER
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_ARCHIVE_CONFIG TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_ARCHIVE_MAPPER TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_ARCHIVE_TYPE TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_CONTENT TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_ERROR TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_GROUPER TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE_ARCHIVE TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE_CERTIFICATE TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE_CREDENTIAL TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE_TOKEN TO I16D_MNG;
GRANT SELECT, INSERT, UPDATE, DELETE ON I16D_VALUE_URL TO I16D_MNG;
--RUNTIME
GRANT SELECT ON I16D_VALUE_CERTIFICATE_VIEW TO I16D_RUN;
