/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "I16D_BEAN_METHOD_VIEW")
public class I16dBeanMethod implements Serializable {

	@Column(name = "BEAN_METHOD_ID", updatable = false, nullable = false, length = 200)
	@Id
	private String beanMethodId;
	@Column(name = "BEAN_ID", updatable = false, insertable = false, length = 150)
	@Basic
	private String beanId;
	@Column(name = "NAME_", updatable = false, insertable = false, nullable = false, length = 200)
	@Basic(optional = false)
	private String name;
	@Column(name = "DESCRIPTION", updatable = false, insertable = false, length = 500)
	@Basic
	private String description;
	@Column(name = "METHOD_SIGNATURE", updatable = false, insertable = false, length = 100)
	@Basic
	private String methodSignature;
	@Column(name = "BEAN_REF", updatable = false, insertable = false, length = 300)
	@Basic
	private String beanRef;
	@Column(name = "BEAN_NAME", updatable = false, insertable = false, nullable = false, length = 300)
	@Basic(optional = false)
	private String beanName;
	@OneToOne(cascade = {CascadeType.ALL}, fetch = FetchType.EAGER, targetEntity = I16dBeanMethodExt.class)
	@JoinColumn(name = "BEAN_METHOD_ID", referencedColumnName = "BEAN_METHOD_ID")
	private I16dBeanMethodExt i16dBeanMethodExt;

	public String getBeanMethodId() {
		return this.beanMethodId;
	}

	public void setBeanMethodId(String beanMethodId) {
		this.beanMethodId = beanMethodId;
	}

	public String getBeanId() {
		return this.beanId;
	}

	public void setBeanId(String beanId) {
		this.beanId = beanId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getMethodSignature() {
		return this.methodSignature;
	}

	public void setMethodSignature(String methodSignature) {
		this.methodSignature = methodSignature;
	}

	public String getBeanRef() {
		return this.beanRef;
	}

	public void setBeanRef(String beanRef) {
		this.beanRef = beanRef;
	}

	public String getBeanName() {
		return this.beanName;
	}

	public void setBeanName(String beanName) {
		this.beanName = beanName;
	}

	public I16dBeanMethodExt getI16dBeanMethodExt() {
		return this.i16dBeanMethodExt;
	}

	public void setI16dBeanMethodExt(I16dBeanMethodExt i16dBeanMethodExt) {
		this.i16dBeanMethodExt = i16dBeanMethodExt;
	}
}