/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author sipaco
 */
@Entity
@Table(name = "I16D_ERROR")
public class I16dError extends AuditPartial {

	@Column(name = "ERROR_ID", columnDefinition = "NUMBER", unique = true, updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_ERROR", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_ERROR", sequenceName = "I16D_SEQ_ERROR")
	private Long errorId;
	@Column(name = "ATTEMPT", columnDefinition = "VARCHAR2(10)", nullable = false, length = 10)
	@Basic(optional = false)
	private String attempt;
	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR2(999)", nullable = false, length = 999)
	@Basic(optional = false)
	private String description;
	@Column(name = "NOM_ARCHIVE", columnDefinition = "VARCHAR2(30)", nullable = false, length = 30)
	@Basic(optional = false)
	private String nomArchive;
	@Column(name = "NAME_COLUMN", columnDefinition = "VARCHAR2(30)", nullable = false, length = 30)
	@Basic(optional = false)
	private String nameColumn;
	@Column(name = "AT_LINE", nullable = false)
	@Basic(optional = false)
	private int atLine;
	@ManyToOne(targetEntity = I16dValueArchive.class)
	@JoinColumn(name = "VALUE_ARCHIVE_ID")
	private I16dValueArchive i16dValueArchive;

	public Long getErrorId() {
		return this.errorId;
	}

	public void setErrorId(Long errorId) {
		this.errorId = errorId;
	}

	public String getAttempt() {
		return this.attempt;
	}

	public void setAttempt(String attempt) {
		this.attempt = attempt;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getNomArchive() {
		return this.nomArchive;
	}

	public void setNomArchive(String nomArchive) {
		this.nomArchive = nomArchive;
	}

	public String getNameColumn() {
		return this.nameColumn;
	}

	public void setNameColumn(String nameColumn) {
		this.nameColumn = nameColumn;
	}

	public int getAtLine() {
		return this.atLine;
	}

	public void setAtLine(int atLine) {
		this.atLine = atLine;
	}

	public I16dValueArchive getI16dValueArchive() {
		return this.i16dValueArchive;
	}

	public void setI16dValueArchive(I16dValueArchive i16dValueArchive) {
		this.i16dValueArchive = i16dValueArchive;
	}
}