/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author sipaco
 */
@Entity
@Table(name = "I16D_CONTENT")
public class I16dContent extends AuditPartial {

	@Column(name = "CONTENT_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_CONTENT", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_CONTENT", sequenceName = "I16D_SEQ_CONTENT")
	private Long contentId;
	@Column(name = "ARCHIVE_CONFIG_ID", columnDefinition = "NUMBER")
	@Basic
	private Long archiveConfigId;
	@Column(name = "NAME_", columnDefinition = "VARCHAR2(50)", length = 50)
	@Basic
	private String name;
	@Column(name = "CONTENT")
	@Lob
	@Basic
	private byte[] content;
	@Column(name = "SUMMARY", columnDefinition = "VARCHAR2(100)", length = 100)
	@Basic
	private String summary;
	@ManyToOne(targetEntity = I16dContent.class)
	@JoinColumn(name = "CONTENT_PARENT_ID")
	private I16dContent i16dParent;
	@OneToMany(targetEntity = I16dContent.class, mappedBy = "i16dParent")
	private List<I16dContent> i16dContentList;

	public Long getContentId() {
		return this.contentId;
	}

	public void setContentId(Long contentId) {
		this.contentId = contentId;
	}

	public Long getArchiveConfigId() {
		return this.archiveConfigId;
	}

	public void setArchiveConfigId(Long archiveConfigId) {
		this.archiveConfigId = archiveConfigId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public byte[] getContent() {
		return this.content;
	}

	public void setContent(byte[] content) {
		this.content = content;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public I16dContent getI16dParent() {
		return this.i16dParent;
	}

	public void setI16dParent(I16dContent i16dParent) {
		this.i16dParent = i16dParent;
	}

	public List<I16dContent> getI16dContentList() {
		return this.i16dContentList;
	}

	public void setI16dContentList(List<I16dContent> i16dContentList) {
		this.i16dContentList = i16dContentList;
	}

	public boolean isI16dContentEmpty() {
		return i16dContentList == null || i16dContentList.isEmpty();
	}
}
