/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.convert.BooleanConvert;
import bo.union.persist.police.AuditPartial;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "I16D_DEPLOYMENT_EXT")
public class I16dDeploymentExt extends AuditPartial implements Serializable {

	@Column(name = "DEPLOYMENT_ID", updatable = false, nullable = false, length = 50)
	@Id
	private String deploymentId;
	@Convert(converter = BooleanConvert.class)
	@Column(name = "ACTIVE_", nullable = false, length = 1)
	@Basic(optional = false)
	private Boolean active;
	@Convert(converter = BooleanConvert.class)
	@Column(name = "LOGGER_", nullable = false, length = 1)
	@Basic(optional = false)
	private Boolean logger;
	@Column(name = "VERSION_ID", nullable = false, length = 100)
	@Basic(optional = false)
	private String versionId;

	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	public Boolean isActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}

	public Boolean isLogger() {
		return this.logger;
	}

	public void setLogger(Boolean logger) {
		this.logger = logger;
	}

	public String getVersionId() {
		return this.versionId;
	}

	public void setVersionId(String versionId) {
		this.versionId = versionId;
	}
}