/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.convert.BooleanConvert;
import bo.union.persist.police.AuditPartial;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

@Entity
@Table(name = "I16D_BEAN_METHOD_EXT")
public class I16dBeanMethodExt extends AuditPartial implements Serializable {

	@Column(name = "BEAN_METHOD_ID", updatable = false, nullable = false, length = 200)
	@Id
	private String beanMethodId;
	@Convert(converter = BooleanConvert.class)
	@Column(name = "ACTIVE_", table = "I16D_BEAN_METHOD_EXT", nullable = false, length = 1)
	@Basic(optional = false)
	private Boolean active;

	public String getBeanMethodId() {
		return this.beanMethodId;
	}

	public void setBeanMethodId(String beanMethodId) {
		this.beanMethodId = beanMethodId;
	}

	public Boolean isActive() {
		return this.active;
	}

	public void setActive(Boolean active) {
		this.active = active;
	}
}