/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import java.util.Date;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author sipaco
 */
@Entity
@Table(name = "I16D_VALUE_ARCHIVE")
public class I16dValueArchive extends AuditPartial implements I16dValueItem {

	@Column(name = "VALUE_ARCHIVE_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_VALUE_ARCHIVE", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_VALUE_ARCHIVE", sequenceName = "I16D_SEQ_VALUE_ARCHIVE")
	private Long valueArchiveId;
	@Column(name = "ATTEMPT_NRO", nullable = false)
	@Basic(optional = false)
	private Integer attemptNro;
	@Column(name = "ATTEMPT_STATE", columnDefinition = "VARCHAR2(20)", nullable = false, length = 20)
	@Basic(optional = false)
	private String attemptState;
	@Column(name = "DATE_FROM", columnDefinition = "TIMESTAMP", nullable = false)
	@Basic(optional = false)
	@Temporal(TemporalType.DATE)
	private Date dateFrom;
	@Column(name = "DATE_TO", columnDefinition = "TIMESTAMP", nullable = false)
	@Basic(optional = false)
	@Temporal(TemporalType.DATE)
	private Date dateTo;
	@ManyToOne(targetEntity = I16dValue.class)
	@JoinColumn(name = "VALUE_ID")
	private I16dValue i16dValue;
	@ManyToOne(targetEntity = I16dArchiveType.class)
	@JoinColumn(name = "ARCHIVE_TYPE_ID")
	private I16dArchiveType i16dArchiveType;
	@ManyToOne(targetEntity = I16dContent.class)
	@JoinColumn(name = "CONTENT_ID")
	private I16dContent i16dContent;
	@OneToMany(targetEntity = I16dError.class, mappedBy = "i16dValueArchive")
	private List<I16dError> i16dErrorList;

	public Long getValueArchiveId() {
		return this.valueArchiveId;
	}

	public void setValueArchiveId(Long valueArchiveId) {
		this.valueArchiveId = valueArchiveId;
	}

	public Integer getAttemptNro() {
		return this.attemptNro;
	}

	public void setAttemptNro(Integer attemptNro) {
		this.attemptNro = attemptNro;
	}

	public String getAttemptState() {
		return this.attemptState;
	}

	public void setAttemptState(String attemptState) {
		this.attemptState = attemptState;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public I16dValue getI16dValue() {
		return this.i16dValue;
	}

	public void setI16dValue(I16dValue i16dValue) {
		this.i16dValue = i16dValue;
	}

	public I16dArchiveType getI16dArchiveType() {
		return this.i16dArchiveType;
	}

	public void setI16dArchiveType(I16dArchiveType i16dArchiveType) {
		this.i16dArchiveType = i16dArchiveType;
	}

	public I16dContent getI16dContent() {
		return this.i16dContent;
	}

	public void setI16dContent(I16dContent i16dContent) {
		this.i16dContent = i16dContent;
	}

	public List<I16dError> getI16dErrorList() {
		return this.i16dErrorList;
	}

	public void setI16dErrorList(List<I16dError> i16dErrorList) {
		this.i16dErrorList = i16dErrorList;
	}
}