/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author wyujra
 */
@Entity
@Table(name = "I16D_GROUPER")
public class I16dGrouper extends AuditPartial {

	@Column(name = "GROUPER_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_GROUPER", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_GROUPER", sequenceName = "I16D_SEQ_GROUPER")
	private Long grouperId;
	@Column(name = "NAME_", columnDefinition = "VARCHAR2(50)", nullable = false, length = 50)
	@Basic
	private String name;
	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR2(200)", nullable = false, length = 200)
	@Basic
	private String description;
	@Column(name = "ALG_TOKEN", columnDefinition = "VARCHAR2(50)", updatable = false, nullable = false, length = 50)
	@Basic
	private String algToken;
	@ManyToOne(targetEntity = I16dGrouper.class)
	@JoinColumn(name = "GROUPER_PARENT_ID")
	private I16dGrouper i16dParent;
	@OneToMany(targetEntity = I16dGrouper.class, mappedBy = "i16dParent")
	private List<I16dGrouper> i16dGrouperList;
	@OneToMany(targetEntity = I16dValue.class, mappedBy = "i16dGrouper")
	private List<I16dValue> i16dValueList;

	public Long getGrouperId() {
		return this.grouperId;
	}

	public void setGrouperId(Long grouperId) {
		this.grouperId = grouperId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAlgToken() {
		return this.algToken;
	}

	public void setAlgToken(String algToken) {
		this.algToken = algToken;
	}

	public I16dGrouper getI16dParent() {
		return this.i16dParent;
	}

	public void setI16dParent(I16dGrouper i16dParent) {
		this.i16dParent = i16dParent;
	}

	public List<I16dGrouper> getI16dGrouperList() {
		return this.i16dGrouperList;
	}

	public void setI16dGrouperList(List<I16dGrouper> i16dGrouperList) {
		this.i16dGrouperList = i16dGrouperList;
	}

	public List<I16dValue> getI16dValueList() {
		return this.i16dValueList;
	}

	public void setI16dValueList(List<I16dValue> i16dValueList) {
		this.i16dValueList = i16dValueList;
	}

	public boolean isI16dGrouperEmpty() {
		return i16dGrouperList == null || i16dGrouperList.isEmpty();
	}
}
