/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.convert.ListConvert;
import bo.union.persist.police.AuditPartial;
import java.util.List;
import javax.persistence.Basic;
import javax.persistence.Cacheable;
import javax.persistence.Column;
import javax.persistence.Convert;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author sipaco
 */
@Entity
@Table(name = "I16D_ARCHIVE_TYPE")
@Cacheable(false)
public class I16dArchiveType extends AuditPartial {

	@Column(name = "ARCHIVE_TYPE_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_ARCHIVE_TYPE", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_ARCHIVE_TYPE", sequenceName = "I16D_SEQ_ARCHIVE_TYPE")
	private Long archiveTypeId;
	@Column(columnDefinition = "VARCHAR2(30)", length = 30)
	@Basic
	private String code;
	@Column(columnDefinition = "VARCHAR2(30)", length = 30)
	@Basic
	private String origin;
	@Column(columnDefinition = "VARCHAR2(30)", length = 30)
	@Basic
	private String sender;
	@Column(columnDefinition = "VARCHAR2(10)", length = 10)
	@Basic
	private String format;
	@Column(columnDefinition = "VARCHAR2(200)", length = 200)
	@Basic
	private String behavior;
	@Column(columnDefinition = "VARCHAR2(100)", length = 100)
	@Basic
	private String description;
	@Convert(converter = ListConvert.class)
	@Column(name = "EMAIL_NOTIFICATION", columnDefinition = "VARCHAR2(200)")
	@Basic
	private List emailList;
	@OneToOne(targetEntity = I16dArchiveConfig.class)
	@JoinColumn(name = "ARCHIVE_CONFIG_ID")
	private I16dArchiveConfig i16dArchiveConfig;

	public String getBehavior() {
		return behavior;
	}

	public void setBehavior(String behavior) {
		this.behavior = behavior;
	}

	public Long getArchiveTypeId() {
		return this.archiveTypeId;
	}

	public void setArchiveTypeId(Long archiveTypeId) {
		this.archiveTypeId = archiveTypeId;
	}

	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	public String getOrigin() {
		return this.origin;
	}

	public void setOrigin(String origin) {
		this.origin = origin;
	}

	public String getSender() {
		return this.sender;
	}

	public void setSender(String sender) {
		this.sender = sender;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public List getEmailList() {
		return this.emailList;
	}

	public void setEmailList(List emailList) {
		this.emailList = emailList;
	}

	public I16dArchiveConfig getI16dArchiveConfig() {
		return this.i16dArchiveConfig;
	}

	public void setI16dArchiveConfig(I16dArchiveConfig i16dArchiveConfig) {
		this.i16dArchiveConfig = i16dArchiveConfig;
	}
}
