/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author wyujra
 */
@Entity
@Table(name = "I16D_VALUE")
public class I16dValue extends AuditPartial {

	@Column(name = "VALUE_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_VALUE", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_VALUE", sequenceName = "I16D_SEQ_VALUE")
	private Long valueId;
	@Column(name = "NAME_", columnDefinition = "VARCHAR2(50)", nullable = false, length = 50)
	@Basic
	private String name;
	@Column(name = "TYPE_", columnDefinition = "VARCHAR2(10)", nullable = false, length = 10)
	@Basic
	private String type;
	@Column(name = "STATE_", columnDefinition = "VARCHAR2(10)", nullable = false, length = 10)
	@Basic
	private String state;
	@Column(name = "DESCRIPTION", columnDefinition = "VARCHAR2(100)", nullable = false, length = 100)
	@Basic
	private String description;
	@ManyToOne(targetEntity = I16dGrouper.class)
	@JoinColumn(name = "GROUPER_ID")
	private I16dGrouper i16dGrouper;

	public Long getValueId() {
		return this.valueId;
	}

	public void setValueId(Long valueId) {
		this.valueId = valueId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public I16dGrouper getI16dGrouper() {
		return this.i16dGrouper;
	}

	public void setI16dGrouper(I16dGrouper i16dGrouper) {
		this.i16dGrouper = i16dGrouper;
	}
}
