/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.OneToOne;
import javax.persistence.Table;

@Entity
@Table(name = "I16D_DEPLOYMENT_VIEW")
public class I16dDeployment implements Serializable {

	@Column(name = "DEPLOYMENT_ID", updatable = false, nullable = false, length = 50)
	@Id
	private String deploymentId;
	@Column(name = "NAME_", updatable = false, insertable = false, length = 100)
	@Basic
	private String name;
	@Column(name = "DESCRIPTION", updatable = false, insertable = false, length = 500)
	@Basic(optional = false)
	private String description;
	@Column(name = "TYPE_", updatable = false, insertable = false, length = 30)
	@Basic(optional = false)
	private String type;
	@Column(name = "SUBTYPE", updatable = false, insertable = false, length = 30)
	@Basic(optional = false)
	private String subtype;
	@OneToOne(cascade = {CascadeType.ALL}, fetch = FetchType.EAGER, targetEntity = I16dDeploymentExt.class)
	@JoinColumn(name = "DEPLOYMENT_ID", referencedColumnName = "DEPLOYMENT_ID")
	private I16dDeploymentExt i16dDeploymentExt;

	public String getDeploymentId() {
		return this.deploymentId;
	}

	public void setDeploymentId(String deploymentId) {
		this.deploymentId = deploymentId;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getSubtype() {
		return this.subtype;
	}

	public void setSubtype(String subtype) {
		this.subtype = subtype;
	}

	public I16dDeploymentExt getI16dDeploymentExt() {
		return this.i16dDeploymentExt;
	}

	public void setI16dDeploymentExt(I16dDeploymentExt i16dDeploymentExt) {
		this.i16dDeploymentExt = i16dDeploymentExt;
	}
}