/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ForeignKey;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * @author sipaco
 */
@Entity
@Table(name = "I16D_ARCHIVE_MAPPER")
public class I16dArchiveMapper extends AuditPartial {

	@Column(name = "ARCHIVE_MAPPER_ID", columnDefinition = "NUMBER", precision = 15)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_ARCHIVE_MAPPER", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_ARCHIVE_MAPPER", sequenceName = "I16D_SEQ_ARCHIVE_MAPPER")
	private Long archiveMapperId;
	@Column(name = "COL_TABLE", columnDefinition = "VARCHAR2(30)", length = 30)
	@Basic
	private String colTable;
	@Column(name = "COL_ARCHIVE", columnDefinition = "VARCHAR2(30)", length = 30)
	@Basic
	private String colArchive;
	@Column(name = "TYPE_", columnDefinition = "VARCHAR2(10)", length = 10)
	@Basic
	private String type;
	@Column(name = "NAME_", columnDefinition = "VARCHAR2(50)", length = 50)
	@Basic
	private String name;
	@Column(name = "FORMAT", columnDefinition = "VARCHAR2(10)", length = 10)
	@Basic
	private String format;
	@Column(name = "IS_REQUIRED", columnDefinition = "VARCHAR2(1)", length = 1)
	@Basic
	private String isRequired;
	@Column(name = "IS_INSERTABLE", columnDefinition = "VARCHAR2(1)", length = 1)
	@Basic
	private String isInsertable;
	@Column(name = "VALUE_INICIAL", columnDefinition = "VARCHAR2(50)", length = 50)
	@Basic
	private String valueInicial;
	@Column(columnDefinition = "VARCHAR2(50)", length = 50)
	@Basic
	private String orderBy;
	@Column(name = "SIZE_VALUE", columnDefinition = "VARCHAR2(10)", precision = 10)
	@Basic
	private int sizeValue;
	@ManyToOne(targetEntity = I16dArchiveConfig.class)
	@JoinColumn(name = "ARCHIVE_CONFIG_ID", foreignKey = @ForeignKey(name = "FK_ARCH_MAPEO_ID_CONF"))
	private I16dArchiveConfig i16dArchiveConfig;

	public Long getArchiveMapperId() {
		return this.archiveMapperId;
	}

	public void setArchiveMapperId(Long archiveMapperId) {
		this.archiveMapperId = archiveMapperId;
	}

	public String getColTable() {
		return this.colTable;
	}

	public void setColTable(String colTable) {
		this.colTable = colTable;
	}

	public String getColArchive() {
		return this.colArchive;
	}

	public void setColArchive(String colArchive) {
		this.colArchive = colArchive;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getFormat() {
		return this.format;
	}

	public void setFormat(String format) {
		this.format = format;
	}

	public String getIsRequired() {
		return this.isRequired;
	}

	public void setIsRequired(String isRequired) {
		this.isRequired = isRequired;
	}

	public String getIsInsertable() {
		return this.isInsertable;
	}

	public void setIsInsertable(String isInsertable) {
		this.isInsertable = isInsertable;
	}

	public String getValueInicial() {
		return this.valueInicial;
	}

	public void setValueInicial(String valueInicial) {
		this.valueInicial = valueInicial;
	}

	public String getOrderBy() {
		return this.orderBy;
	}

	public void setOrderBy(String orderBy) {
		this.orderBy = orderBy;
	}

	public int getSizeValue() {
		return this.sizeValue;
	}

	public void setSizeValue(int sizeValue) {
		this.sizeValue = sizeValue;
	}

	public I16dArchiveConfig getI16dArchiveConfig() {
		return this.i16dArchiveConfig;
	}

	public void setI16dArchiveConfig(I16dArchiveConfig i16dArchiveConfig) {
		this.i16dArchiveConfig = i16dArchiveConfig;
	}
}
