/**
 *  ____                          _   _       _    __
 * | __ )  __ _ _ __   ___ ___   | | | |_ __ (_) _/_/ _ __
 * |  _ \ / _` | '_ \ / __/ _ \  | | | | '_ \| |/ _ \| '_ \
 * | |_) | (_| | | | | (_| (_) | | |_| | | | | | (_) | | | |
 * |____/ \__,_|_| |_|\___\___/   \___/|_| |_|_|\___/|_| |_|
 *  ____                            _           ____
 * |  _ \ _ __ ___  _   _  ___  ___| |_ ___    / ___|___  _ __ ___
 * | |_) | '__/ _ \| | | |/ _ \/ __| __/ _ \  | |   / _ \| '__/ _ \
 * |  __/| | | (_) | |_| |  __/ (__| || (_) | | |__| (_) | | |  __/
 * |_|   |_|  \___/ \__, |\___|\___|\__\___/   \____\___/|_|  \___|
 *                  |___/
 *
 * Copyright © 2017 - http://union.dev/licence.txt#yracnet
 */
/**
 * This file was generated by the Jeddict
 */
package bo.union.platform.i16d.manager.entity;

import bo.union.persist.police.AuditPartial;
import java.util.Date;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.Lob;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * @author wyujra
 */
@Entity
@Table(name = "I16D_VALUE_CERTIFICATE")
public class I16dValueCertificate extends AuditPartial implements I16dValueItem {

	@Column(name = "VALUE_CERTIFICATE_ID", columnDefinition = "NUMBER", updatable = false, nullable = false)
	@Id
	@GeneratedValue(generator = "I16D_SEQ_VALUE_CERTIFICATE", strategy = GenerationType.SEQUENCE)
	@SequenceGenerator(name = "I16D_SEQ_VALUE_CERTIFICATE", sequenceName = "I16D_SEQ_VALUE_CERTIFICATE")
	private Long valueCertificateId;
	@Column(name = "TYPE_", columnDefinition = "VARCHAR2(20)", nullable = false, length = 20)
	@Basic
	private String type;
	@Column(name = "ARCHIVE", nullable = false)
	@Lob
	@Basic
	private byte[] archive;
	@Column(name = "PASSWORD", columnDefinition = "VARCHAR2(100)", length = 100)
	@Basic
	private String password;
	@Column(name = "SUMMARY", nullable = false, length = 200)
	@Basic
	private String summary;
	@Column(name = "NAME_SIGNATURE", columnDefinition = "VARCHAR2(20)", nullable = false, length = 20)
	@Basic
	private String nameSignature;
	@Column(name = "ALG_SIGNTURE", columnDefinition = "VARCHAR2(20)", length = 20)
	@Basic
	private String algSignture;
	@Column(name = "ALG_DIGEST", columnDefinition = "VARCHAR2(20)", length = 20)
	@Basic
	private String algDigest;
	@Column(name = "ALG_ENCRYPT", columnDefinition = "VARCHAR2(20)", length = 20)
	@Basic
	private String algEncrypt;
	@Column(name = "DATE_FROM", columnDefinition = "TIMESTAMP", nullable = false)
	@Basic(optional = false)
	@Temporal(TemporalType.DATE)
	private Date dateFrom;
	@Column(name = "DATE_TO", columnDefinition = "TIMESTAMP", nullable = false)
	@Basic(optional = false)
	@Temporal(TemporalType.DATE)
	private Date dateTo;
	@ManyToOne(targetEntity = I16dValue.class)
	@JoinColumn(name = "VALUE_ID")
	private I16dValue i16dValue;

	public Long getValueCertificateId() {
		return this.valueCertificateId;
	}

	public void setValueCertificateId(Long valueCertificateId) {
		this.valueCertificateId = valueCertificateId;
	}

	public String getType() {
		return this.type;
	}

	public void setType(String type) {
		this.type = type;
	}

	public byte[] getArchive() {
		return this.archive;
	}

	public void setArchive(byte[] archive) {
		this.archive = archive;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getSummary() {
		return this.summary;
	}

	public void setSummary(String summary) {
		this.summary = summary;
	}

	public String getNameSignature() {
		return this.nameSignature;
	}

	public void setNameSignature(String nameSignature) {
		this.nameSignature = nameSignature;
	}

	public String getAlgSignture() {
		return this.algSignture;
	}

	public void setAlgSignture(String algSignture) {
		this.algSignture = algSignture;
	}

	public String getAlgDigest() {
		return this.algDigest;
	}

	public void setAlgDigest(String algDigest) {
		this.algDigest = algDigest;
	}

	public String getAlgEncrypt() {
		return this.algEncrypt;
	}

	public void setAlgEncrypt(String algEncrypt) {
		this.algEncrypt = algEncrypt;
	}

	public Date getDateFrom() {
		return this.dateFrom;
	}

	public void setDateFrom(Date dateFrom) {
		this.dateFrom = dateFrom;
	}

	public Date getDateTo() {
		return this.dateTo;
	}

	public void setDateTo(Date dateTo) {
		this.dateTo = dateTo;
	}

	public I16dValue getI16dValue() {
		return this.i16dValue;
	}

	public void setI16dValue(I16dValue i16dValue) {
		this.i16dValue = i16dValue;
	}
}
